cuda_devices: [0,1,2]
task_names: ''
hydra:
  run:
    dir: ./workdir/logs/${now:%Y-%m-%d}/${now:%H-%M-%S}
    
tasks:
    - 
        name: 'distilbert'
        config_path: '../configs'
        config_name: 'al_cls'
        command: '../../active_learning/run_active_learning.py'
        environ: ''
        args: 'data.dataset_name=ag_news acquisition_model.name=distilbert-base-uncased'
        seeds: [4837, 23419, 705525, 10671619, 1084218]
        n_repeats: 1