output_dir: './workdir/run_active_learning'
hydra:
  run:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${to_string:${acquisition_model.name}}_${to_string:${successor_model.name}}
  sweep:
    dir: ${output_dir}/${now:%Y-%m-%d}/${now:%H-%M-%S}_${seed}_${to_string:${acquisition_model.name}}_${to_string:${successor_model.name}}
    subdir: ${hydra.job.num}
    
seed: 42
cuda_device: 0
cache_dir: ./${output_dir}/cache_${seed}_${to_string:${acquisition_model.name}}
cache_model_and_dataset: False
framework: ???
task: 'ner'
offline_mode: False

data:
    dataset_name: 'conll2003'
    path: '../data/'
    tag_index: 2
    text_name: 'tokens'
    label_name: 'ner_tags'
    labels_to_remove:
    seed: ${seed}

acquisition_model:
    type: ${task}
    name: 'distilbert-base-cased'
    tokenizer_max_length:
    loss: 'cross-entropy'
    classifier_dropout: 0.
    exists_in_repo: True # whether the model exists in HF models repo
    path_to_pretrained: # required if the model does not exist in HF models repo
    training:
        dev_size: 0.
        shuffle_dev: False
        freeze_embedder: False
        batch_size_args:
            batch_size: 16
            eval_batch_size: 100
            min_num_gradient_steps: 1000
            adjust_batch_size: True
            adjust_num_epochs: True
            min_batch_size: 4
        trainer_args:
            num_epochs: 15
            patience: ${get_patience_value:${acquisition_model.training.dev_size}}
            grad_clipping: 1.
            serialization_dir: ./output/${to_string:${acquisition_model.name}}_${seed}_${now:%Y-%m-%d}_${now:%H-%M-%S}/acquisition
            validation_metric: ${framework.validation_metric_ner}
            evaluation_strategy: 'no' # for transformers wrapper, 'epoch' or 'steps' or 'no'
            eval_metrics:
            fp16:
                training: True
                evaluation: False
            accumulation:
                gradient_accumulation_steps: 1
                eval_accumulation_steps:
        optimizer_args:
            weight_decay: 0.01
            lr: 5e-5
        scheduler_args:
            warmup_steps_factor: 0.1
            use_adafactor: False

successor_model:
    type: ${task}
    name: 'bert-base-cased'
    tokenizer_max_length:
    loss: 'cross-entropy'
    classifier_dropout: 0.
    exists_in_repo: True # whether the model exists in HF models repo
    path_to_pretrained: # required if the model does not exist in HF models repo
    training:
        dev_size: 0.
        shuffle_dev: False
        freeze_embedder: False
        batch_size_args:
            batch_size: 16
            eval_batch_size: 100
            min_num_gradient_steps: 1000
            adjust_batch_size: True
            adjust_num_epochs: True
            min_batch_size: 4
        trainer_args:
            num_epochs: 15
            patience: ${get_patience_value:${successor_model.training.dev_size}}
            grad_clipping: 1.
            serialization_dir: ./output/${to_string:${acquisition_model.name}}_${seed}_${now:%Y-%m-%d}_${now:%H-%M-%S}/successor
            validation_metric: ${framework.validation_metric_ner}
            evaluation_strategy: 'no' # for transformers wrapper, 'epoch' or 'steps' or 'no'
            eval_metrics:
            fp16:
                training: True
                evaluation: False
            accumulation:
                gradient_accumulation_steps: 1
                eval_accumulation_steps:
        optimizer_args:
            weight_decay: 0.01
            lr: 5e-5
        scheduler_args:
            warmup_steps_factor: 0.1
            use_adafactor: False

target_model:
    type: ${task}
    name: 'google/electra-base-discriminator'
    tokenizer_max_length:
    loss: 'cross-entropy'
    classifier_dropout: 0.
    exists_in_repo: True # whether the model exists in HF models repo
    path_to_pretrained: # required if the model does not exist in HF models repo
    training:
        pseudo_labeled_label_smoothing: False
        labeled_weight: 1
        dev_size: 0.
        shuffle_dev: False
        freeze_embedder: False
        batch_size_args:
            batch_size: 16
            eval_batch_size: 100
            min_num_gradient_steps: 350
            adjust_batch_size: True
            adjust_num_epochs: True
            min_batch_size: 4
        trainer_args:
            num_epochs: 5
            patience: ${get_patience_value:${target_model.training.dev_size}}
            grad_clipping: 1.
            serialization_dir: ./output/${to_string:${acquisition_model.name}}_${seed}_${now:%Y-%m-%d}_${now:%H-%M-%S}/target
            validation_metric: ${framework.validation_metric_ner}
            evaluation_strategy: 'epoch' # for transformers wrapper, 'epoch' or 'steps' or 'no'
            eval_metrics:
            fp16:
                training: True
                evaluation: False
            final_model_fp16:
                training: True
                evaluation: False
            accumulation:
                gradient_accumulation_steps: 1
                eval_accumulation_steps:
        optimizer_args:
            weight_decay: 0.01
            lr: 5e-5
        scheduler_args:
            warmup_steps_factor: 0.1
            use_adafactor: False

al:
    strategy: 'mnlp'
    num_queries: 15
    init_p_or_n: 0.02
    step_p_or_n: 0.02
    split_by_tokens: True
    gamma_or_k_confident_to_save: 0.1
    T: 0.01
    sampling_type:
    iters_to_recalc_scores: [0, 1, 4, 8]
    evaluate_query: True
    strategy_kwargs:

tracin:
    use: False
    quantiles: [-1]
    max_num_processes: 5
    num_model_checkpoints: 3
    nu: 1

defaults:
  - framework: transformers # 'allennlp' or 'transformers'
